---

- name: Build BricksLLM
  ansible.builtin.command:
    cmd: go build -ldflags="-s -w" -o ./bin/bricksllm ./cmd/bricksllm/main.go
  args:
    chdir: "{{ bricksllm_home }}/BricksLLM"
    creates: "{{ bricksllm_home }}/BricksLLM/bin/bricksllm"
  become: yes
  become_user: "{{ bricksllm_user }}"

- name: Set env file
  ansible.builtin.template:
    src: default-env.j2
    dest: "{{ bricksllm_home }}/BricksLLM/bin/.env"
    mode: '0600'
    owner: "{{ bricksllm_user }}"

# FIXME! systemd?
