---

- name: Proxy
  when:
    - proxy_env != None
    - proxy_env|length > 0
  block:
    # FIXME! still need to add proxy env variables to Dockerfile...
    - name: Ensure .docker directory exists
      ansible.builtin.file:
        path: "{{ bricksllm_home }}/.docker"
        mode: '0700'
        owner: "{{ bricksllm_user }}"
        state: directory
    - name: Add docker proxy configuration
      ansible.builtin.template:
        src: docker-config.json.j2
        dest: "{{ bricksllm_home }}/.docker/config.json"
        mode: '0600'
        owner: "{{ bricksllm_user }}"
      become: yes
      become_user: "{{ bricksllm_user }}"
