---

- name: Verify
  hosts: "{{ playbook_hosts | default('all') }}"
  vars:
    test_dns:
      - github.com
      - proxy.golang.org
    processes:
      - { u: root, p: dockerd }
    ports:
      # postgres
      - { h: 127.0.0.1, p: 5432 }
      # redis
      - { h: 127.0.0.1, p: 6379 }
      # bricksllm
      - { h: 127.0.0.1, p: 8080 }
    is_container: false
  pre_tasks:
    - name: RedHat | Ensure ps is present
      ansible.builtin.package:
        name: procps-ng
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 8
    - name: Debian | Ensure ps is present
      ansible.builtin.package:
        name: procps
        state: present
      when: ansible_os_family == "Debian"
    - name: Debug | var ansible_virtualization_type
      ansible.builtin.debug:
        var: ansible_virtualization_type
    - name: Set fact is_container
      ansible.builtin.set_fact:
        is_container: true
      when: >
        (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker"
           or ansible_virtualization_type == "containerd"
           or ansible_virtualization_type == "container"
          )
        )
  tasks:
    - name: Ensure processes are running
      ansible.builtin.command:
        cmd: "pgrep -u {{ item.u }} {{ item.p }}"
      register: ps
      changed_when: false
      failed_when: false
      loop: "{{ processes }}"
    - name: Validate ps output
      ansible.builtin.assert:
        that:
          - item.stdout | length > 0
      loop: "{{ ps.results }}"
      when:
        - not is_container|bool
      ignore_errors: true  # noqa ignore-errors

    - name: Check all processes
      ansible.builtin.command: ps aux
      changed_when: false
      register: psa
    - name: Debug | ps aux output
      ansible.builtin.debug:
        var: psa
        verbosity: 1

    - name: Ensure ports are listening
      ansible.builtin.wait_for:
        host: "{{ item.h }}"
        port: "{{ item.p }}"
        timeout: 10
      with_items: "{{ ports }}"
      when:
        - not is_container|bool

    - name: Test DNS resolution
      ansible.builtin.command:
        cmd: "host {{ item }}"
      changed_when: false
      register: dig_dns
      loop: "{{ test_dns }}"
